"""MSJ Activities Calendar 2026–2027.

Source: Activities_Calendar_2026-2027 (Google Sheets export).
ASB / Leadership events are collapsed for planning; athletics, council,
and testing rows feed the iCal subscription only.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Literal

Category = Literal["asb", "council", "athletics", "testing"]

@dataclass(frozen=True, slots=True)
class ActivitiesCalendarEntry:
    name: str
    slug: str
    starts_on: date
    ends_on: date | None = None
    category: Category = "athletics"

    @property
    def needs_planning(self) -> bool:
        return self.category == "asb"

    @property
    def year(self) -> int:
        return self.starts_on.year


ACTIVITIES_CALENDAR_YEAR_LABEL = "2026-2027"

# Canonical Leadership / ASB events (one row per production).
ASB_PLANNING_EVENTS: tuple[ActivitiesCalendarEntry, ...] = (
    ActivitiesCalendarEntry(
        name='Maze Day',
        slug='maze-day-2026',
        starts_on=date.fromisoformat("2026-08-06"),
        ends_on=date.fromisoformat("2026-08-07"),
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Green & White Rally',
        slug='green-white-rally-2026',
        starts_on=date.fromisoformat("2026-08-21"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Kickoff Week',
        slug='kickoff-week-2026',
        starts_on=date.fromisoformat("2026-09-14"),
        ends_on=date.fromisoformat("2026-09-18"),
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Homecoming Kickoff (L2) Assembly',
        slug='homecoming-kickoff-2026',
        starts_on=date.fromisoformat("2026-09-21"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Freshmen (CO30) Homecoming',
        slug='homecoming-frosh-2026',
        starts_on=date.fromisoformat("2026-09-22"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Sophomores (CO29) Homecoming',
        slug='homecoming-soph-2026',
        starts_on=date.fromisoformat("2026-09-23"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Juniors (CO28) Homecoming',
        slug='homecoming-junior-2026',
        starts_on=date.fromisoformat("2026-09-24"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Seniors (CO27) Homecoming',
        slug='homecoming-senior-2026',
        starts_on=date.fromisoformat("2026-09-25"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='HCX Dance',
        slug='hcx-dance-2026',
        starts_on=date.fromisoformat("2026-09-25"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Fall Rally',
        slug='fall-rally-2026',
        starts_on=date.fromisoformat("2026-10-09"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Winter Rally',
        slug='winter-rally-2027',
        starts_on=date.fromisoformat("2027-01-15"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Winter Ball Dance',
        slug='winter-ball-2027',
        starts_on=date.fromisoformat("2027-02-19"),
        ends_on=None,
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='MC Week',
        slug='mc-week-2027',
        starts_on=date.fromisoformat("2027-04-05"),
        ends_on=date.fromisoformat("2027-04-09"),
        category="asb",
    ),
    ActivitiesCalendarEntry(
        name='Spring Rally (Awards)',
        slug='spring-rally-2027',
        starts_on=date.fromisoformat("2027-05-17"),
        ends_on=None,
        category="asb",
    ),
)

# Council, athletics, and testing — iCal only (status=calendar).
CALENDAR_ONLY_ENTRIES: tuple[ActivitiesCalendarEntry, ...] = (
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-08-12-council-c120',
        starts_on=date.fromisoformat("2026-08-12"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-08-19-council-c120',
        starts_on=date.fromisoformat("2026-08-19"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2026-08-22-sat-test',
        starts_on=date.fromisoformat("2026-08-22"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-08-26-council-c120',
        starts_on=date.fromisoformat("2026-08-26"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: MSJ, Moreau @ Spring Valley',
        slug='activities-2026-09-01-g-golf-msj-moreau-spring-valley',
        starts_on=date.fromisoformat("2026-09-01"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-09-02-council-c120',
        starts_on=date.fromisoformat("2026-09-02"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='XC: 2 Mile "MVAL Opener" by grade level @ Newark Memorial',
        slug='activities-2026-09-02-xc-2-mile-mval-opener-by-grade-level-newark-memorial',
        starts_on=date.fromisoformat("2026-09-02"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: Irvington @ MSJ',
        slug='activities-2026-09-08-g-vball-irvington-msj',
        starts_on=date.fromisoformat("2026-09-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-09-09-council-c120',
        starts_on=date.fromisoformat("2026-09-09"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='WP: MSJ @ Newark Memorial',
        slug='activities-2026-09-09-wp-msj-newark-memorial',
        starts_on=date.fromisoformat("2026-09-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='XC: MVAL Center Meet #1 @ Mission San Jose',
        slug='activities-2026-09-09-xc-mval-center-meet-1-mission-san-jose',
        starts_on=date.fromisoformat("2026-09-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: Irvington, Newark Memorial, MSJ @ Mission Hills',
        slug='activities-2026-09-10-g-golf-irvington-newark-memorial-msj-mission-hills',
        starts_on=date.fromisoformat("2026-09-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: Moreau @ MSJ',
        slug='activities-2026-09-10-g-vball-moreau-msj',
        starts_on=date.fromisoformat("2026-09-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2026-09-12-sat-test',
        starts_on=date.fromisoformat("2026-09-12"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: Irvington @ MSJ',
        slug='activities-2026-09-15-g-tennis-irvington-msj',
        starts_on=date.fromisoformat("2026-09-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ Kennedy',
        slug='activities-2026-09-15-g-vball-msj-kennedy',
        starts_on=date.fromisoformat("2026-09-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-09-16-council-c120',
        starts_on=date.fromisoformat("2026-09-16"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: American, MSJ @ San Ramon',
        slug='activities-2026-09-16-g-golf-american-msj-san-ramon',
        starts_on=date.fromisoformat("2026-09-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='WP: American @ MSJ',
        slug='activities-2026-09-16-wp-american-msj',
        starts_on=date.fromisoformat("2026-09-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: Moreau @ MSJ',
        slug='activities-2026-09-17-g-tennis-moreau-msj',
        starts_on=date.fromisoformat("2026-09-17"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: American @ MSJ',
        slug='activities-2026-09-17-g-vball-american-msj',
        starts_on=date.fromisoformat("2026-09-17"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: Kennedy @ MSJ',
        slug='activities-2026-09-22-g-tennis-kennedy-msj',
        starts_on=date.fromisoformat("2026-09-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ James Logan',
        slug='activities-2026-09-22-g-vball-msj-james-logan',
        starts_on=date.fromisoformat("2026-09-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-09-23-council-c120',
        starts_on=date.fromisoformat("2026-09-23"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: MSJ, Washington, American @ Mission Hills',
        slug='activities-2026-09-24-g-golf-msj-washington-american-mission-hills',
        starts_on=date.fromisoformat("2026-09-24"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: American @ MSJ',
        slug='activities-2026-09-24-g-tennis-american-msj',
        starts_on=date.fromisoformat("2026-09-24"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ Washington',
        slug='activities-2026-09-24-g-vball-msj-washington',
        starts_on=date.fromisoformat("2026-09-24"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: Washington, MSJ @ Spring Valley',
        slug='activities-2026-09-29-g-golf-washington-msj-spring-valley',
        starts_on=date.fromisoformat("2026-09-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ James Logan',
        slug='activities-2026-09-29-g-tennis-msj-james-logan',
        starts_on=date.fromisoformat("2026-09-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ Newark Memorial',
        slug='activities-2026-09-29-g-vball-msj-newark-memorial',
        starts_on=date.fromisoformat("2026-09-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-09-30-council-c120',
        starts_on=date.fromisoformat("2026-09-30"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='WP: MSJ @ Irvington',
        slug='activities-2026-09-30-wp-msj-irvington',
        starts_on=date.fromisoformat("2026-09-30"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='XC: MVAL Center Meet #2 @ Quarry Lakes',
        slug='activities-2026-09-30-xc-mval-center-meet-2-quarry-lakes',
        starts_on=date.fromisoformat("2026-09-30"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: Moreau, MSJ, Irvington @ Mission Hills',
        slug='activities-2026-10-01-g-golf-moreau-msj-irvington-mission-hills',
        starts_on=date.fromisoformat("2026-10-01"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: Washington @ MSJ',
        slug='activities-2026-10-01-g-tennis-washington-msj',
        starts_on=date.fromisoformat("2026-10-01"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ Irvington',
        slug='activities-2026-10-01-g-vball-msj-irvington',
        starts_on=date.fromisoformat("2026-10-01"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2026-10-03-sat-test',
        starts_on=date.fromisoformat("2026-10-03"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='G Golf: MSJ, Newark Memorial @ San Ramon',
        slug='activities-2026-10-06-g-golf-msj-newark-memorial-san-ramon',
        starts_on=date.fromisoformat("2026-10-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ Newark Memorial',
        slug='activities-2026-10-06-g-tennis-msj-newark-memorial',
        starts_on=date.fromisoformat("2026-10-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ Moreau',
        slug='activities-2026-10-06-g-vball-msj-moreau',
        starts_on=date.fromisoformat("2026-10-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-10-07-council-c120',
        starts_on=date.fromisoformat("2026-10-07"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='WP: James Logan @ MSJ',
        slug='activities-2026-10-07-wp-james-logan-msj',
        starts_on=date.fromisoformat("2026-10-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='XC: MVAL Frosh/Soph Challenge #1 @ Garin Park',
        slug='activities-2026-10-07-xc-mval-frosh-soph-challenge-1-garin-park',
        starts_on=date.fromisoformat("2026-10-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ Irvington',
        slug='activities-2026-10-08-g-tennis-msj-irvington',
        starts_on=date.fromisoformat("2026-10-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: Kennedy @ MSJ',
        slug='activities-2026-10-08-g-vball-kennedy-msj',
        starts_on=date.fromisoformat("2026-10-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ Moreau',
        slug='activities-2026-10-13-g-tennis-msj-moreau',
        starts_on=date.fromisoformat("2026-10-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: MSJ @ American',
        slug='activities-2026-10-13-g-vball-msj-american',
        starts_on=date.fromisoformat("2026-10-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-10-14-council-c120',
        starts_on=date.fromisoformat("2026-10-14"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='WP: Washington @ MSJ',
        slug='activities-2026-10-14-wp-washington-msj',
        starts_on=date.fromisoformat("2026-10-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='XC: MVAL Center Meet #3 @ Newark Memorial',
        slug='activities-2026-10-14-xc-mval-center-meet-3-newark-memorial',
        starts_on=date.fromisoformat("2026-10-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ Kennedy',
        slug='activities-2026-10-15-g-tennis-msj-kennedy',
        starts_on=date.fromisoformat("2026-10-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: James Logan @ MSJ',
        slug='activities-2026-10-15-g-vball-james-logan-msj',
        starts_on=date.fromisoformat("2026-10-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ American',
        slug='activities-2026-10-20-g-tennis-msj-american',
        starts_on=date.fromisoformat("2026-10-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: Washington @ MSJ',
        slug='activities-2026-10-20-g-vball-washington-msj',
        starts_on=date.fromisoformat("2026-10-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-10-21-council-c120',
        starts_on=date.fromisoformat("2026-10-21"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='WP: MSJ @ Moreau',
        slug='activities-2026-10-21-wp-msj-moreau',
        starts_on=date.fromisoformat("2026-10-21"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='XC: MVAL Frosh/Soph Challenge #2 @ Mission San Jose',
        slug='activities-2026-10-21-xc-mval-frosh-soph-challenge-2-mission-san-jose',
        starts_on=date.fromisoformat("2026-10-21"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: James Logan @ MSJ',
        slug='activities-2026-10-22-g-tennis-james-logan-msj',
        starts_on=date.fromisoformat("2026-10-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Vball: Newark Memorial @ MSJ',
        slug='activities-2026-10-22-g-vball-newark-memorial-msj',
        starts_on=date.fromisoformat("2026-10-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: MSJ @ Washington',
        slug='activities-2026-10-27-g-tennis-msj-washington',
        starts_on=date.fromisoformat("2026-10-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-10-28-council-c120',
        starts_on=date.fromisoformat("2026-10-28"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Tennis: Newark Memorial @ MSJ',
        slug='activities-2026-10-29-g-tennis-newark-memorial-msj',
        starts_on=date.fromisoformat("2026-10-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-11-04-council-c120',
        starts_on=date.fromisoformat("2026-11-04"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='XC: MVAL Championships @ Quarry Lakes',
        slug='activities-2026-11-04-xc-mval-championships-quarry-lakes',
        starts_on=date.fromisoformat("2026-11-04"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2026-11-07-sat-test',
        starts_on=date.fromisoformat("2026-11-07"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-11-11-council-c120',
        starts_on=date.fromisoformat("2026-11-11"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-11-18-council-c120',
        starts_on=date.fromisoformat("2026-11-18"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-11-25-council-c120',
        starts_on=date.fromisoformat("2026-11-25"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-12-02-council-c120',
        starts_on=date.fromisoformat("2026-12-02"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2026-12-05-sat-test',
        starts_on=date.fromisoformat("2026-12-05"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ Newark Memorial',
        slug='activities-2026-12-08-b-bball-msj-newark-memorial',
        starts_on=date.fromisoformat("2026-12-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: Newark Memorial @ MSJ',
        slug='activities-2026-12-08-g-bball-newark-memorial-msj',
        starts_on=date.fromisoformat("2026-12-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: Newark Memorial @ MSJ',
        slug='activities-2026-12-09-b-soccer-newark-memorial-msj',
        starts_on=date.fromisoformat("2026-12-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-12-09-council-c120',
        starts_on=date.fromisoformat("2026-12-09"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Wrestling: Irvington @ MSJ',
        slug='activities-2026-12-09-wrestling-irvington-msj',
        starts_on=date.fromisoformat("2026-12-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ James Logan',
        slug='activities-2026-12-15-b-bball-msj-james-logan',
        starts_on=date.fromisoformat("2026-12-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: James Logan @ MSJ',
        slug='activities-2026-12-15-g-bball-james-logan-msj',
        starts_on=date.fromisoformat("2026-12-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ Irvington',
        slug='activities-2026-12-15-g-soccer-msj-irvington',
        starts_on=date.fromisoformat("2026-12-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: Kennedy @ MSJ',
        slug='activities-2026-12-16-b-soccer-kennedy-msj',
        starts_on=date.fromisoformat("2026-12-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-12-16-council-c120',
        starts_on=date.fromisoformat("2026-12-16"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Wrestling: MSJ @ Kennedy',
        slug='activities-2026-12-16-wrestling-msj-kennedy',
        starts_on=date.fromisoformat("2026-12-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: Newark Memorial @ MSJ',
        slug='activities-2026-12-17-g-soccer-newark-memorial-msj',
        starts_on=date.fromisoformat("2026-12-17"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: Moreau @ MSJ',
        slug='activities-2026-12-18-b-soccer-moreau-msj',
        starts_on=date.fromisoformat("2026-12-18"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-12-23-council-c120',
        starts_on=date.fromisoformat("2026-12-23"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2026-12-30-council-c120',
        starts_on=date.fromisoformat("2026-12-30"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: Kennedy @ MSJ',
        slug='activities-2027-01-05-b-bball-kennedy-msj',
        starts_on=date.fromisoformat("2027-01-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ Kennedy',
        slug='activities-2027-01-05-g-bball-msj-kennedy',
        starts_on=date.fromisoformat("2027-01-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: American @ MSJ',
        slug='activities-2027-01-05-g-soccer-american-msj',
        starts_on=date.fromisoformat("2027-01-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: James Logan @ MSJ',
        slug='activities-2027-01-06-b-soccer-james-logan-msj',
        starts_on=date.fromisoformat("2027-01-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-01-06-council-c120',
        starts_on=date.fromisoformat("2027-01-06"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Wrestling: James Logan @ MSJ',
        slug='activities-2027-01-06-wrestling-james-logan-msj',
        starts_on=date.fromisoformat("2027-01-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: Washington @ MSJ',
        slug='activities-2027-01-07-b-bball-washington-msj',
        starts_on=date.fromisoformat("2027-01-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ Washington',
        slug='activities-2027-01-07-g-bball-msj-washington',
        starts_on=date.fromisoformat("2027-01-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ Kennedy',
        slug='activities-2027-01-07-g-soccer-msj-kennedy',
        starts_on=date.fromisoformat("2027-01-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: Washington @ MSJ',
        slug='activities-2027-01-08-b-soccer-washington-msj',
        starts_on=date.fromisoformat("2027-01-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ Moreau',
        slug='activities-2027-01-12-b-bball-msj-moreau',
        starts_on=date.fromisoformat("2027-01-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: Moreau @ MSJ',
        slug='activities-2027-01-12-g-bball-moreau-msj',
        starts_on=date.fromisoformat("2027-01-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: Moreau @ MSJ',
        slug='activities-2027-01-12-g-soccer-moreau-msj',
        starts_on=date.fromisoformat("2027-01-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ Irvington',
        slug='activities-2027-01-13-b-soccer-msj-irvington',
        starts_on=date.fromisoformat("2027-01-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-01-13-council-c120',
        starts_on=date.fromisoformat("2027-01-13"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Wrestling: MSJ @ American',
        slug='activities-2027-01-13-wrestling-msj-american',
        starts_on=date.fromisoformat("2027-01-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: American @ MSJ',
        slug='activities-2027-01-14-b-bball-american-msj',
        starts_on=date.fromisoformat("2027-01-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ American',
        slug='activities-2027-01-14-g-bball-msj-american',
        starts_on=date.fromisoformat("2027-01-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: James Logan @ MSJ',
        slug='activities-2027-01-14-g-soccer-james-logan-msj',
        starts_on=date.fromisoformat("2027-01-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: Irvington @ MSJ',
        slug='activities-2027-01-19-b-bball-irvington-msj',
        starts_on=date.fromisoformat("2027-01-19"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ Irvington',
        slug='activities-2027-01-19-g-bball-msj-irvington',
        starts_on=date.fromisoformat("2027-01-19"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: Washington @ MSJ',
        slug='activities-2027-01-19-g-soccer-washington-msj',
        starts_on=date.fromisoformat("2027-01-19"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ American',
        slug='activities-2027-01-20-b-soccer-msj-american',
        starts_on=date.fromisoformat("2027-01-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-01-20-council-c120',
        starts_on=date.fromisoformat("2027-01-20"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Wrestling: MSJ @ Newark Memorial',
        slug='activities-2027-01-20-wrestling-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-01-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: Irvington @ MSJ',
        slug='activities-2027-01-21-g-soccer-irvington-msj',
        starts_on=date.fromisoformat("2027-01-21"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: Newark Memorial @ MSJ',
        slug='activities-2027-01-22-b-bball-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-01-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ Kennedy',
        slug='activities-2027-01-22-b-soccer-msj-kennedy',
        starts_on=date.fromisoformat("2027-01-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ Newark Memorial',
        slug='activities-2027-01-22-g-bball-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-01-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: Irvington @ MSJ',
        slug='activities-2027-01-25-b-soccer-irvington-msj',
        starts_on=date.fromisoformat("2027-01-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ Newark Memorial',
        slug='activities-2027-01-26-g-soccer-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-01-26"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Wrestling: Washington @ MSJ',
        slug='activities-2027-01-26-wrestling-washington-msj',
        starts_on=date.fromisoformat("2027-01-26"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: James Logan @ MSJ',
        slug='activities-2027-01-27-b-bball-james-logan-msj',
        starts_on=date.fromisoformat("2027-01-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ Moreau',
        slug='activities-2027-01-27-b-soccer-msj-moreau',
        starts_on=date.fromisoformat("2027-01-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-01-27-council-c120',
        starts_on=date.fromisoformat("2027-01-27"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ James Logan',
        slug='activities-2027-01-27-g-bball-msj-james-logan',
        starts_on=date.fromisoformat("2027-01-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ American',
        slug='activities-2027-01-28-g-soccer-msj-american',
        starts_on=date.fromisoformat("2027-01-28"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ Kennedy',
        slug='activities-2027-01-29-b-bball-msj-kennedy',
        starts_on=date.fromisoformat("2027-01-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ James Logan',
        slug='activities-2027-01-29-b-soccer-msj-james-logan',
        starts_on=date.fromisoformat("2027-01-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: Kennedy @ MSJ',
        slug='activities-2027-01-29-g-bball-kennedy-msj',
        starts_on=date.fromisoformat("2027-01-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: Kennedy @ MSJ',
        slug='activities-2027-02-02-g-soccer-kennedy-msj',
        starts_on=date.fromisoformat("2027-02-02"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ Washington',
        slug='activities-2027-02-03-b-bball-msj-washington',
        starts_on=date.fromisoformat("2027-02-03"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ Washington',
        slug='activities-2027-02-03-b-soccer-msj-washington',
        starts_on=date.fromisoformat("2027-02-03"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-02-03-council-c120',
        starts_on=date.fromisoformat("2027-02-03"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: Washington @ MSJ',
        slug='activities-2027-02-03-g-bball-washington-msj',
        starts_on=date.fromisoformat("2027-02-03"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ Moreau',
        slug='activities-2027-02-04-g-soccer-msj-moreau',
        starts_on=date.fromisoformat("2027-02-04"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: Moreau @ MSJ',
        slug='activities-2027-02-05-b-bball-moreau-msj',
        starts_on=date.fromisoformat("2027-02-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: MSJ @ Moreau',
        slug='activities-2027-02-05-g-bball-msj-moreau',
        starts_on=date.fromisoformat("2027-02-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ James Logan',
        slug='activities-2027-02-09-g-soccer-msj-james-logan',
        starts_on=date.fromisoformat("2027-02-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ American',
        slug='activities-2027-02-10-b-bball-msj-american',
        starts_on=date.fromisoformat("2027-02-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: MSJ @ Newark Memorial',
        slug='activities-2027-02-10-b-soccer-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-02-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-02-10-council-c120',
        starts_on=date.fromisoformat("2027-02-10"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: American @ MSJ',
        slug='activities-2027-02-10-g-bball-american-msj',
        starts_on=date.fromisoformat("2027-02-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Soccer: MSJ @ Washington',
        slug='activities-2027-02-11-g-soccer-msj-washington',
        starts_on=date.fromisoformat("2027-02-11"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Bball: MSJ @ Irvington',
        slug='activities-2027-02-12-b-bball-msj-irvington',
        starts_on=date.fromisoformat("2027-02-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Soccer: American @ MSJ',
        slug='activities-2027-02-12-b-soccer-american-msj',
        starts_on=date.fromisoformat("2027-02-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='G Bball: Irvington @ MSJ',
        slug='activities-2027-02-12-g-bball-irvington-msj',
        starts_on=date.fromisoformat("2027-02-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-02-17-council-c120',
        starts_on=date.fromisoformat("2027-02-17"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-02-24-council-c120',
        starts_on=date.fromisoformat("2027-02-24"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: James Logan, MSJ @ Redwood Canyon',
        slug='activities-2027-02-25-b-golf-james-logan-msj-redwood-canyon',
        starts_on=date.fromisoformat("2027-02-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: Tom Crocker Relays @ Newark Memorial',
        slug='activities-2027-02-27-swim-tom-crocker-relays-newark-memorial',
        starts_on=date.fromisoformat("2027-02-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ Irvington',
        slug='activities-2027-03-02-b-tennis-msj-irvington',
        starts_on=date.fromisoformat("2027-03-02"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-03-03-council-c120',
        starts_on=date.fromisoformat("2027-03-03"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Track: MVAL Center Meet 1a @ James Logan',
        slug='activities-2027-03-03-track-mval-center-meet-1a-james-logan',
        starts_on=date.fromisoformat("2027-03-03"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: MSJ, Washington @ Redwood Canyon',
        slug='activities-2027-03-04-b-golf-msj-washington-redwood-canyon',
        starts_on=date.fromisoformat("2027-03-04"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: Newark Memorial @ MSJ',
        slug='activities-2027-03-04-b-tennis-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-03-04"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: Washington @ MSJ',
        slug='activities-2027-03-05-swim-washington-msj',
        starts_on=date.fromisoformat("2027-03-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2027-03-06-sat-test',
        starts_on=date.fromisoformat("2027-03-06"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: American @ MSJ',
        slug='activities-2027-03-09-b-tennis-american-msj',
        starts_on=date.fromisoformat("2027-03-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: Washington @ MSJ',
        slug='activities-2027-03-09-b-vball-washington-msj',
        starts_on=date.fromisoformat("2027-03-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ Moreau',
        slug='activities-2027-03-09-badminton-msj-moreau',
        starts_on=date.fromisoformat("2027-03-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: American, MSJ @ Spring Valley',
        slug='activities-2027-03-10-b-golf-american-msj-spring-valley',
        starts_on=date.fromisoformat("2027-03-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-03-10-council-c120',
        starts_on=date.fromisoformat("2027-03-10"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Track: MVAL Center Meet 1b @ Moreau Catholic',
        slug='activities-2027-03-10-track-mval-center-meet-1b-moreau-catholic',
        starts_on=date.fromisoformat("2027-03-10"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: Irvington, MSJ @ Redwood Canyon',
        slug='activities-2027-03-11-b-golf-irvington-msj-redwood-canyon',
        starts_on=date.fromisoformat("2027-03-11"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ Kennedy',
        slug='activities-2027-03-11-b-tennis-msj-kennedy',
        starts_on=date.fromisoformat("2027-03-11"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ Kennedy',
        slug='activities-2027-03-11-b-vball-msj-kennedy',
        starts_on=date.fromisoformat("2027-03-11"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: James Logan @ MSJ',
        slug='activities-2027-03-11-badminton-james-logan-msj',
        starts_on=date.fromisoformat("2027-03-11"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: MSJ @ Irvington',
        slug='activities-2027-03-12-swim-msj-irvington',
        starts_on=date.fromisoformat("2027-03-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: Irvington, James Logan, MSJ @ San Ramon',
        slug='activities-2027-03-16-b-golf-irvington-james-logan-msj-san-ramon',
        starts_on=date.fromisoformat("2027-03-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: Moreau @ MSJ',
        slug='activities-2027-03-16-b-tennis-moreau-msj',
        starts_on=date.fromisoformat("2027-03-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: American @ MSJ',
        slug='activities-2027-03-16-b-vball-american-msj',
        starts_on=date.fromisoformat("2027-03-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ Washington',
        slug='activities-2027-03-16-badminton-msj-washington',
        starts_on=date.fromisoformat("2027-03-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: James Logan @ MSJ',
        slug='activities-2027-03-16-softball-james-logan-msj',
        starts_on=date.fromisoformat("2027-03-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-03-17-council-c120',
        starts_on=date.fromisoformat("2027-03-17"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: MSJ, Moreau Catholic @ Redwood Canyon',
        slug='activities-2027-03-18-b-golf-msj-moreau-catholic-redwood-canyon',
        starts_on=date.fromisoformat("2027-03-18"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ James Logan',
        slug='activities-2027-03-18-b-tennis-msj-james-logan',
        starts_on=date.fromisoformat("2027-03-18"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ Moreau',
        slug='activities-2027-03-18-b-vball-msj-moreau',
        starts_on=date.fromisoformat("2027-03-18"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: Irvington @ MSJ',
        slug='activities-2027-03-18-badminton-irvington-msj',
        starts_on=date.fromisoformat("2027-03-18"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: Washington @ MSJ',
        slug='activities-2027-03-18-softball-washington-msj',
        starts_on=date.fromisoformat("2027-03-18"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: Newark Memorial @ MSJ',
        slug='activities-2027-03-19-swim-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-03-19"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: Washington @ MSJ',
        slug='activities-2027-03-23-b-tennis-washington-msj',
        starts_on=date.fromisoformat("2027-03-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: James Logan @ MSJ',
        slug='activities-2027-03-23-b-vball-james-logan-msj',
        starts_on=date.fromisoformat("2027-03-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ Newark Memorial',
        slug='activities-2027-03-23-badminton-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-03-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ James Logan',
        slug='activities-2027-03-23-baseball-msj-james-logan',
        starts_on=date.fromisoformat("2027-03-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ Irvington',
        slug='activities-2027-03-23-softball-msj-irvington',
        starts_on=date.fromisoformat("2027-03-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-03-24-council-c120',
        starts_on=date.fromisoformat("2027-03-24"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Track: MVAL Center Meet 2 @ Newark Memorial',
        slug='activities-2027-03-24-track-mval-center-meet-2-newark-memorial',
        starts_on=date.fromisoformat("2027-03-24"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: Irvington @ MSJ',
        slug='activities-2027-03-25-b-tennis-irvington-msj',
        starts_on=date.fromisoformat("2027-03-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ Newark Memorial',
        slug='activities-2027-03-25-b-vball-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-03-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: American @ MSJ',
        slug='activities-2027-03-25-badminton-american-msj',
        starts_on=date.fromisoformat("2027-03-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: James Logan @ MSJ',
        slug='activities-2027-03-25-baseball-james-logan-msj',
        starts_on=date.fromisoformat("2027-03-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: Newark Memorial @ MSJ',
        slug='activities-2027-03-25-softball-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-03-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: American @ MSJ',
        slug='activities-2027-03-25-swim-american-msj',
        starts_on=date.fromisoformat("2027-03-25"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-03-31-council-c120',
        starts_on=date.fromisoformat("2027-03-31"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: MSJ, Moreau Catholic, Newark Memorial @ San Ramon',
        slug='activities-2027-04-06-b-golf-msj-moreau-catholic-newark-memorial-san-ramon',
        starts_on=date.fromisoformat("2027-04-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ Newark Memorial',
        slug='activities-2027-04-06-b-tennis-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-04-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ Irvington',
        slug='activities-2027-04-06-b-vball-msj-irvington',
        starts_on=date.fromisoformat("2027-04-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: Kennedy @ MSJ',
        slug='activities-2027-04-06-badminton-kennedy-msj',
        starts_on=date.fromisoformat("2027-04-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: Washington @ MSJ',
        slug='activities-2027-04-07-baseball-washington-msj',
        starts_on=date.fromisoformat("2027-04-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Track: MVAL Center Meet 3a @ TAK (IHS)',
        slug='activities-2027-04-07-track-mval-center-meet-3a-tak-ihs',
        starts_on=date.fromisoformat("2027-04-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ American',
        slug='activities-2027-04-08-b-tennis-msj-american',
        starts_on=date.fromisoformat("2027-04-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ Washington',
        slug='activities-2027-04-08-b-vball-msj-washington',
        starts_on=date.fromisoformat("2027-04-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: Moreau @ MSJ',
        slug='activities-2027-04-08-badminton-moreau-msj',
        starts_on=date.fromisoformat("2027-04-08"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ Washington',
        slug='activities-2027-04-09-baseball-msj-washington',
        starts_on=date.fromisoformat("2027-04-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: MSJ @ Kennedy',
        slug='activities-2027-04-09-swim-msj-kennedy',
        starts_on=date.fromisoformat("2027-04-09"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: American, MSJ, Washington @ San Ramon',
        slug='activities-2027-04-13-b-golf-american-msj-washington-san-ramon',
        starts_on=date.fromisoformat("2027-04-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: Kennedy @ MSJ',
        slug='activities-2027-04-13-b-tennis-kennedy-msj',
        starts_on=date.fromisoformat("2027-04-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: Kennedy @ MSJ',
        slug='activities-2027-04-13-b-vball-kennedy-msj',
        starts_on=date.fromisoformat("2027-04-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ James Logan',
        slug='activities-2027-04-13-badminton-msj-james-logan',
        starts_on=date.fromisoformat("2027-04-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: American @ MSJ',
        slug='activities-2027-04-13-softball-american-msj',
        starts_on=date.fromisoformat("2027-04-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Golf: MSJ, Newark Memorial @ Spring Valley',
        slug='activities-2027-04-14-b-golf-msj-newark-memorial-spring-valley',
        starts_on=date.fromisoformat("2027-04-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ Irvington',
        slug='activities-2027-04-14-baseball-msj-irvington',
        starts_on=date.fromisoformat("2027-04-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-04-14-council-c120',
        starts_on=date.fromisoformat("2027-04-14"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Track: MVAL Center Meet 3b @ TAK (JFKHS)',
        slug='activities-2027-04-14-track-mval-center-meet-3b-tak-jfkhs',
        starts_on=date.fromisoformat("2027-04-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ Moreau',
        slug='activities-2027-04-15-b-tennis-msj-moreau',
        starts_on=date.fromisoformat("2027-04-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ American',
        slug='activities-2027-04-15-b-vball-msj-american',
        starts_on=date.fromisoformat("2027-04-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: Washington @ MSJ',
        slug='activities-2027-04-15-badminton-washington-msj',
        starts_on=date.fromisoformat("2027-04-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ Kennedy',
        slug='activities-2027-04-15-softball-msj-kennedy',
        starts_on=date.fromisoformat("2027-04-15"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: Irvington @ MSJ',
        slug='activities-2027-04-16-baseball-irvington-msj',
        starts_on=date.fromisoformat("2027-04-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: Moreau @ MSJ',
        slug='activities-2027-04-16-swim-moreau-msj',
        starts_on=date.fromisoformat("2027-04-16"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: James Logan @ MSJ',
        slug='activities-2027-04-20-b-tennis-james-logan-msj',
        starts_on=date.fromisoformat("2027-04-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: Moreau @ MSJ',
        slug='activities-2027-04-20-b-vball-moreau-msj',
        starts_on=date.fromisoformat("2027-04-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ Irvington',
        slug='activities-2027-04-20-badminton-msj-irvington',
        starts_on=date.fromisoformat("2027-04-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: Moreau @ MSJ',
        slug='activities-2027-04-20-softball-moreau-msj',
        starts_on=date.fromisoformat("2027-04-20"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: Newark Memorial @ MSJ',
        slug='activities-2027-04-21-baseball-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-04-21"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-04-21-council-c120',
        starts_on=date.fromisoformat("2027-04-21"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='B Tennis: MSJ @ Washington',
        slug='activities-2027-04-22-b-tennis-msj-washington',
        starts_on=date.fromisoformat("2027-04-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: MSJ @ James Logan',
        slug='activities-2027-04-22-b-vball-msj-james-logan',
        starts_on=date.fromisoformat("2027-04-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: Newark Memorial @ MSJ',
        slug='activities-2027-04-22-badminton-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-04-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ James Logan',
        slug='activities-2027-04-22-softball-msj-james-logan',
        starts_on=date.fromisoformat("2027-04-22"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ Newark Memorial',
        slug='activities-2027-04-23-baseball-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-04-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Swim: MSJ @ James Logan',
        slug='activities-2027-04-23-swim-msj-james-logan',
        starts_on=date.fromisoformat("2027-04-23"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: Newark Memorial @ MSJ',
        slug='activities-2027-04-27-b-vball-newark-memorial-msj',
        starts_on=date.fromisoformat("2027-04-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ American',
        slug='activities-2027-04-27-badminton-msj-american',
        starts_on=date.fromisoformat("2027-04-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ Washington',
        slug='activities-2027-04-27-softball-msj-washington',
        starts_on=date.fromisoformat("2027-04-27"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: American @ MSJ',
        slug='activities-2027-04-28-baseball-american-msj',
        starts_on=date.fromisoformat("2027-04-28"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-04-28-council-c120',
        starts_on=date.fromisoformat("2027-04-28"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='B Vball: Irvington @ MSJ',
        slug='activities-2027-04-29-b-vball-irvington-msj',
        starts_on=date.fromisoformat("2027-04-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Badminton: MSJ @ Kennedy',
        slug='activities-2027-04-29-badminton-msj-kennedy',
        starts_on=date.fromisoformat("2027-04-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Softball: Irvington @ MSJ',
        slug='activities-2027-04-29-softball-irvington-msj',
        starts_on=date.fromisoformat("2027-04-29"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ American',
        slug='activities-2027-04-30-baseball-msj-american',
        starts_on=date.fromisoformat("2027-04-30"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2027-05-01-sat-test',
        starts_on=date.fromisoformat("2027-05-01"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-03-ap-testing',
        starts_on=date.fromisoformat("2027-05-03"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-04-ap-testing',
        starts_on=date.fromisoformat("2027-05-04"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ Newark Memorial',
        slug='activities-2027-05-04-softball-msj-newark-memorial',
        starts_on=date.fromisoformat("2027-05-04"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-05-ap-testing',
        starts_on=date.fromisoformat("2027-05-05"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: Kennedy @ MSJ',
        slug='activities-2027-05-05-baseball-kennedy-msj',
        starts_on=date.fromisoformat("2027-05-05"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-05-05-council-c120',
        starts_on=date.fromisoformat("2027-05-05"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-06-ap-testing',
        starts_on=date.fromisoformat("2027-05-06"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ American',
        slug='activities-2027-05-06-softball-msj-american',
        starts_on=date.fromisoformat("2027-05-06"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-07-ap-testing',
        starts_on=date.fromisoformat("2027-05-07"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ Kennedy',
        slug='activities-2027-05-07-baseball-msj-kennedy',
        starts_on=date.fromisoformat("2027-05-07"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-10-ap-testing',
        starts_on=date.fromisoformat("2027-05-10"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-11-ap-testing',
        starts_on=date.fromisoformat("2027-05-11"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Softball: Kennedy @ MSJ',
        slug='activities-2027-05-11-softball-kennedy-msj',
        starts_on=date.fromisoformat("2027-05-11"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-12-ap-testing',
        starts_on=date.fromisoformat("2027-05-12"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: Moreau @ MSJ',
        slug='activities-2027-05-12-baseball-moreau-msj',
        starts_on=date.fromisoformat("2027-05-12"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-05-12-council-c120',
        starts_on=date.fromisoformat("2027-05-12"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-13-ap-testing',
        starts_on=date.fromisoformat("2027-05-13"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Softball: MSJ @ Moreau',
        slug='activities-2027-05-13-softball-msj-moreau',
        starts_on=date.fromisoformat("2027-05-13"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='AP Testing',
        slug='activities-2027-05-14-ap-testing',
        starts_on=date.fromisoformat("2027-05-14"),
        category='testing',
    ),
    ActivitiesCalendarEntry(
        name='Baseball: MSJ @ Moreau',
        slug='activities-2027-05-14-baseball-msj-moreau',
        starts_on=date.fromisoformat("2027-05-14"),
        category='athletics',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-05-19-council-c120',
        starts_on=date.fromisoformat("2027-05-19"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-05-26-council-c120',
        starts_on=date.fromisoformat("2027-05-26"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='Council (C120)',
        slug='activities-2027-06-02-council-c120',
        starts_on=date.fromisoformat("2027-06-02"),
        category='council',
    ),
    ActivitiesCalendarEntry(
        name='SAT TEST',
        slug='activities-2027-06-05-sat-test',
        starts_on=date.fromisoformat("2027-06-05"),
        category='testing',
    ),
)

def all_entries() -> tuple[ActivitiesCalendarEntry, ...]:
    return ASB_PLANNING_EVENTS + CALENDAR_ONLY_ENTRIES

